import type { AppProps } from "next/app"
import Head from "next/head"
import { useLoadScript } from "@react-google-maps/api"

import { FavorisCountryContextProvider } from "@/context/favorisCountryContext"
import Navbar from "@/components/navbar"

import { ChakraProvider } from "@chakra-ui/react"

import "@/styles/globals.css"


export default function Index({ Component, pageProps }: AppProps) {
    const { isLoaded } = useLoadScript({
        googleMapsApiKey: "AIzaSyDbr6FgqPsctO5kXmIFoYL7X7TuaXAGX_o",
        libraries: ["places"],
    })

    if (!isLoaded) return <div>Loading...</div>

    return (<ChakraProvider>
        <FavorisCountryContextProvider>
            <Head>
                <title>Météo Pas France</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar isLoaded={isLoaded} />
            <Component {...pageProps} isLoaded={isLoaded} />
        </FavorisCountryContextProvider>
    </ChakraProvider>)
}