import type { AppProps } from "next/app"
import Head from "next/head"
import { useLoadScript } from "@react-google-maps/api"

import { FavorisCountryContextProvider } from "@/context/favorisCountryContext"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"

import { ChakraProvider } from "@chakra-ui/react"

import "@/styles/globals.css"
import React from "react"


export default function Index({ Component, pageProps }: AppProps) {
    const { isLoaded } = useLoadScript({
        googleMapsApiKey: "AIzaSyDbr6FgqPsctO5kXmIFoYL7X7TuaXAGX_o",
        libraries: ["places"],
    })

    if (!isLoaded) return <div>Loading...</div>

    return (
        <div style={{ width: "100%", height: "100%" }}><ChakraProvider>
            <FavorisCountryContextProvider>
                <Head>
                    <title>PREVISIONS METEO</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/logo.png" type="image/png" />
                </Head>
                <Navbar isLoaded={isLoaded} />
                <div id="appDiv">
                    <Component {...pageProps} isLoaded={isLoaded} />
                </div>
                <Footer />

            </FavorisCountryContextProvider>
        </ChakraProvider>
        </div>)
}